/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Public;

import Classes.Contact;
import Connection.DatabaseConnection;
import Connection.UserDB;
import java.sql.Connection;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.SwingWorker;

/**
 *
 * @author Name of the User
 */
public class ProgressBarTest extends javax.swing.JFrame {

    /**
     * Creates new form ProgressBarTest
     */
    public DatabaseConnection dbcon;
    public Connection con;
    //private ProgressConnect connect;
    
    public ProgressBarTest() {
        initComponents();
    }
    
    public ProgressBarTest(Contact campContact) {
        initComponents();
        SwingWorker sw = new SwingWorker() {
            @Override
            protected Void doInBackground() {
                prog_connect.setIndeterminate(true);
                UserDB udb = new UserDB();
                boolean valid = udb.validate(campContact);
                if (valid) {
                    JOptionPane.showMessageDialog(null, "Successfully registered. ");
                }
                else {
                    JOptionPane.showMessageDialog(null, "Error! \nPossible errors: " + udb.getError());
                }
                return null;
            }
            
            @Override
            protected void done() {
                prog_connect.setIndeterminate(false);
                setVisible(false);
            }
        };
        sw.execute();
    }

//    class ProgressConnect extends SwingWorker<Void, Void> {
//        
//        @Override
//        public Void doInBackground() throws Exception {
//            return null;
//        }
//        
//        @Override
//        public void done() {
//            
//        }
//    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        prog_connect = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        prog_connect.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel1.add(prog_connect, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 240, 20));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("Submitting...");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgressBarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgressBarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgressBarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgressBarTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgressBarTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar prog_connect;
    // End of variables declaration//GEN-END:variables
}
