import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import static javax.swing.JOptionPane.ERROR_MESSAGE;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Name of the User
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    
    Connection con;
    DatabaseConnection DBCon;
    Statement st;
    ResultSet rs;
    PreparedStatement pst;
    DefaultTableModel model;
    String remote = "192.168.1.20";
    
    public MainForm() throws ClassNotFoundException {
        String ip = JOptionPane.showInputDialog(null, "Enter Remote Machine Address: ");
        if (!ip.equals(this.remote)) {
            JOptionPane.showMessageDialog(null, "Wrong remote address, Program Terminated. ", "NYC 2017 Registration", ERROR_MESSAGE);
            System.exit(0);
        }
        else {
            JOptionPane.showMessageDialog(null, "Connected Successfully ", "NYC 2017 Registration", INFORMATION_MESSAGE);
            initComponents();
            DBCon = new DatabaseConnection(ip);
            con = DBCon.getConnection();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    void RefreshTable() {
        model = new DefaultTableModel(new String[]{"ID", "Name", "Age", "Gender", "District", "Group", "BS Leader"}, 0);
        String query = "SELECT id, name, age, gender, district, campergroup, bsleader FROM contactinformation where churchpos != 'Staff' or 'staff'";
        try {
            st = con.createStatement();
            rs = st.executeQuery(query);
            while (rs.next()) {
                String id = rs.getString("id");
                String name = rs.getString("name");
                String age = rs.getString("age");
                String gender = rs.getString("gender");
                String district = rs.getString("district");
                String group = rs.getString("campergroup");
                String bsleader = rs.getString("bsleader");
                model.addRow(new Object[]{id, name, age, gender, district, group, bsleader});
            }
            tbl_responses.setModel(model);
            btn_set.setEnabled(false);
            btn_delete.setEnabled(false);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(null, "The Database is Empty. ", "NYC 2017 Registration", WARNING_MESSAGE);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "The Server is Offline. ", "NYC 2017 Registration", WARNING_MESSAGE);
        }
    }
    
    void filter(String query) {
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<>(model);
        tbl_responses.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" + query));
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        btn_view1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        pnl_view = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_responses = new javax.swing.JTable();
        btn_set = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_group = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_minimize = new javax.swing.JLabel();
        FilterField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_refresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        SidePanel.setBackground(new java.awt.Color(41, 128, 185));

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NYC");

        jLabel4.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Registration");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("2017");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Current Build: v2.0 (12/21/17)");

        btn_view1.setBackground(new java.awt.Color(52, 152, 219));

        label1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("View Responses");

        javax.swing.GroupLayout btn_view1Layout = new javax.swing.GroupLayout(btn_view1);
        btn_view1.setLayout(btn_view1Layout);
        btn_view1Layout.setHorizontalGroup(
            btn_view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_view1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(label1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btn_view1Layout.setVerticalGroup(
            btn_view1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btn_view1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5))
                    .addGroup(SidePanelLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel4)))
                .addGap(29, 29, 29)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_view1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(466, 466, 466)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(SidePanel);

        MainPanel.setBackground(new java.awt.Color(255, 255, 255));
        MainPanel.setLayout(new java.awt.CardLayout());

        pnl_view.setBackground(new java.awt.Color(255, 255, 255));
        pnl_view.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(236, 240, 241));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semilight", 0, 20)); // NOI18N
        jLabel1.setText("Responses");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addContainerGap(791, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        pnl_view.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 930, 60));

        jScrollPane1.setBorder(null);

        tbl_responses.setAutoCreateRowSorter(true);
        tbl_responses.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tbl_responses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Age", "Gender", "District", "Group", "BS Leader"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_responses.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_responses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_responsesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_responses);

        pnl_view.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 830, 440));

        btn_set.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_set.setText("Set Group");
        btn_set.setEnabled(false);
        btn_set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setActionPerformed(evt);
            }
        });
        pnl_view.add(btn_set, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 670, 90, -1));

        btn_delete.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_delete.setText("Delete Response");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        pnl_view.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 670, -1, -1));

        btn_group.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btn_group.setText("View Group");
        btn_group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_groupActionPerformed(evt);
            }
        });
        pnl_view.add(btn_group, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 670, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel6.setText("X");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pnl_view.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 0, -1, -1));

        btn_minimize.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        btn_minimize.setText("_");
        btn_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_minimizeMouseClicked(evt);
            }
        });
        pnl_view.add(btn_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, -30, 20, 70));

        FilterField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        FilterField.setToolTipText("filter");
        FilterField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FilterFieldKeyReleased(evt);
            }
        });
        pnl_view.add(FilterField, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 140, 160, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Filter:");
        pnl_view.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, -1, -1));

        btn_refresh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_refresh.setText("Load/Refresh");
        btn_refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshActionPerformed(evt);
            }
        });
        pnl_view.add(btn_refresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        MainPanel.add(pnl_view, "card2");

        getContentPane().add(MainPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        int option = JOptionPane.showConfirmDialog(null, "Are you sure you wanna exit?", "NYC 2017 Registration", WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
        else {
            
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void btn_setActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setActionPerformed
        int row = tbl_responses.getSelectedRow();
        String id = (tbl_responses.getModel().getValueAt(row, 0)).toString();
        try {
            int group = Integer.parseInt(JOptionPane.showInputDialog(null, "Group: "));
            String query = "UPDATE contactinformation SET campergroup = " + group + " WHERE id = '" + id + "'";
            pst = con.prepareStatement(query);
            pst.execute();
            RefreshTable();
            btn_set.setEnabled(false);
            btn_delete.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error updating group. ");
        }
    }//GEN-LAST:event_btn_setActionPerformed

    private void tbl_responsesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_responsesMouseClicked
        btn_set.setEnabled(true);
        btn_delete.setEnabled(true);
    }//GEN-LAST:event_tbl_responsesMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        DefaultTableModel model = (DefaultTableModel)tbl_responses.getModel();
        int option = JOptionPane.showConfirmDialog(null, "Delete this response? ", "NYC 2017 Registration", WARNING_MESSAGE);
        if (option == JOptionPane.YES_OPTION) {
            int row = tbl_responses.getSelectedRow();
            String id = (tbl_responses.getModel().getValueAt(row, 0)).toString();
            int modelRow = tbl_responses.convertRowIndexToModel( row );
            model.removeRow( modelRow );

            String query = "delete from contactinformation where id = ?";
            try {
                pst = con.prepareStatement(query);
                pst.setString(1, id);
                pst.executeUpdate();
                pst.close();
            } catch (Exception e) {

            }
            btn_set.setEnabled(false);
            btn_delete.setEnabled(false);
        }
        else {
            JOptionPane.showMessageDialog(null, "Deletion Canceled.", "NYC 2017 Registration", INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void FilterFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FilterFieldKeyReleased
        String query = FilterField.getText();
        filter(query);
    }//GEN-LAST:event_FilterFieldKeyReleased

    private void btn_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_btn_minimizeMouseClicked

    private void btn_refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshActionPerformed
        RefreshTable();
    }//GEN-LAST:event_btn_refreshActionPerformed

    private void btn_groupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_groupActionPerformed
        int group = Integer.parseInt(JOptionPane.showInputDialog(null, "Group: "));
        ViewForm vf = new ViewForm(group, this.remote);
        vf.setVisible(true);
    }//GEN-LAST:event_btn_groupActionPerformed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainForm().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField FilterField;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_group;
    private javax.swing.JLabel btn_minimize;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JButton btn_set;
    private javax.swing.JPanel btn_view1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label1;
    private javax.swing.JPanel pnl_view;
    private javax.swing.JTable tbl_responses;
    // End of variables declaration//GEN-END:variables
}
